apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
    version: v1.1
  name: reverseproxy
spec:
  replicas: 2
  selector:
     matchLabels:
       service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
        version: v1.1
    spec:
      containers:
      - image: jimhu79/reverseproxy
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always


